#!/bin/sh
# 20-xbattbar: Restart xbattbar (Battery Bar)
# -a: AC/Battery status, -t: thickness, -T: show on top of windows, -O: color

pkill xbattbar
xbattbar -a -t 2 -T -O yellow bottom 1>/dev/null 2>&1 &
